
/**
Constructor
Do not call Function in Constructor.
*/
class FriendsItemView()
{
	super();

	//TODO:edit here

}
extends AView;


function FriendsItemView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function FriendsItemView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function FriendsItemView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
