
/**
Constructor
Do not call Function in Constructor.
*/
class SlideItem2()
{
	super();

	//TODO:edit here

}
extends AView;


function SlideItem2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SlideItem2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SlideItem2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
