
/**
Constructor
Do not call Function in Constructor.
*/
class SlideItem1()
{
	super();

	//TODO:edit here

}
extends AView;


function SlideItem1*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SlideItem1*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SlideItem1*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
