
/**
Constructor
Do not call Function in Constructor.
*/
class ViewItems()
{
	super();

	//TODO:edit here

}
extends AView;


function ViewItems*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function ViewItems*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function ViewItems*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
