
/**
Constructor
Do not call Function in Constructor.
*/
class ItemView()
{
	super();

	//TODO:edit here

}
extends AView;


function ItemView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function ItemView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function ItemView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
