
/**
Constructor
Do not call Function in Constructor.
*/
class AddSkillItemView()
{
	super();

	//TODO:edit here

}
extends AView;


function AddSkillItemView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function AddSkillItemView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function AddSkillItemView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
