
/**
Constructor
Do not call Function in Constructor.
*/
class HomeTabListItemView()
{
	super();

	//TODO:edit here

}
extends AView;


function HomeTabListItemView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function HomeTabListItemView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function HomeTabListItemView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
