
/**
Constructor
Do not call Function in Constructor.
*/
class RoadListItem()
{
	super();

	//TODO:edit here

}
extends AView;


function RoadListItem*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function RoadListItem*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function RoadListItem*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
