
/**
Constructor
Do not call Function in Constructor.
*/
class HomeView()
{
	super();

	//TODO:edit here

}
extends AView;


function HomeView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here
};

function HomeView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function HomeView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
