
/**
Constructor
Do not call Function in Constructor.
*/
class articleView()
{
	super();

	//TODO:edit here

}
extends AView;


function articleView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function articleView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function articleView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
