
/**
Constructor
Do not call Function in Constructor.
*/
class footerView()
{
	super();

	//TODO:edit here

}
extends AView;


function footerView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function footerView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function footerView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
