
/**
Constructor
Do not call Function in Constructor.
*/
class showMenuView()
{
	super();

	//TODO:edit here

}
extends AView;


function showMenuView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function showMenuView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function showMenuView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
