
/**
Constructor
Do not call Function in Constructor.
*/
class HomeTabListView()
{
	super();

	//TODO:edit here

}
extends AView;


function HomeTabListView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function HomeTabListView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function HomeTabListView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
