
/**
Constructor
Do not call Function in Constructor.
*/
class NoticeView()
{
	super();

	//TODO:edit here

}
extends AView;


function NoticeView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function NoticeView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function NoticeView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
