
/**
Constructor
Do not call Function in Constructor.
*/
class subView2()
{
	super();

	//TODO:edit here

}
extends AView;


function subView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
