
/**
Constructor
Do not call Function in Constructor.
*/
class subView3()
{
	super();

	//TODO:edit here

}
extends AView;


function subView3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function subView3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function subView3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
