
/**
Constructor
Do not call Function in Constructor.
*/
class DetailHomeItemView()
{
	super();

	//TODO:edit here

}
extends AView;


function DetailHomeItemView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DetailHomeItemView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DetailHomeItemView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
