
/**
Constructor
Do not call Function in Constructor.
*/
class DetailUserView()
{
	super();

	//TODO:edit here

}
extends AView;


function DetailUserView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DetailUserView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DetailUserView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
