
/**
Constructor
Do not call Function in Constructor.
*/
class KeywordNotiView()
{
	super();

	//TODO:edit here

}
extends AView;


function KeywordNotiView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function KeywordNotiView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function KeywordNotiView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
