
/**
Constructor
Do not call Function in Constructor.
*/
class MoreEduView()
{
	super();

	//TODO:edit here

}
extends AView;


function MoreEduView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function MoreEduView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function MoreEduView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
