
/**
Constructor
Do not call Function in Constructor.
*/
class RegistUserView()
{
	super();

	//TODO:edit here

}
extends AView;


function RegistUserView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function RegistUserView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function RegistUserView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
