
/**
Constructor
Do not call Function in Constructor.
*/
class CenterNavView()
{
	super();

	//TODO:edit here

}
extends AView;


function CenterNavView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function CenterNavView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function CenterNavView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function CenterNavView*onAViewClick(comp, info, e)
{
	console.log(this.owner);
	//TODO:edit here

};
