
/**
Constructor
Do not call Function in Constructor.
*/
class ClientView()
{
	super();

	//TODO:edit here

}
extends AView;


function ClientView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function ClientView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function ClientView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
