
/**
Constructor
Do not call Function in Constructor.
*/
class CommunityTabView()
{
	super();

	//TODO:edit here

}
extends AView;


function CommunityTabView*init(context, evtListener)
{
	super.init(context, evtListener);
	
	//TODO:edit here

};

function CommunityTabView*onInitDone()
{
	super.onInitDone();
/*	var container = this.communityTab.loadContainer(null);
	var navi = new ANavigator('navi', container);
	
	navi.registerPage('Source/ContainerViews/CommunitySectionView/CommunitySectionView.lay','communitySectionView');
	navi.registerPage('Source/ContainerViews/CommunitySectionView/CommunitySectionView/QaSectionView/QaSectionView.lay', 'qaSectionView');
	
	navi.goPage('communitySectionView');*/
/*	var communityListUrl =
	[
		'Source/ContainerViews/CommunitySectionView/CommunitySectionView.lay',
	]
	//TODO:edit here
	this.communityTab.add*/
};

function CommunityTabView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
