
/**
Constructor
Do not call Function in Constructor.
*/
class DetailView3()
{
	super();

	//TODO:edit here

}
extends AView;


function DetailView3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DetailView3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DetailView3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
