
/**
Constructor
Do not call Function in Constructor.
*/
class DetailView()
{
	super();

	//TODO:edit here

}
extends AView;


function DetailView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DetailView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DetailView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
