
/**
Constructor
Do not call Function in Constructor.
*/
class DetailView2()
{
	super();

	//TODO:edit here

}
extends AView;


function DetailView2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DetailView2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DetailView2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
