
/**
Constructor
Do not call Function in Constructor.
*/
class DocSectionView()
{
	super();

	//TODO:edit here

}
extends AView;


function DocSectionView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function DocSectionView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function DocSectionView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
