
/**
Constructor
Do not call Function in Constructor.
*/
class FooterView()
{
	super();

	//TODO:edit here

}
extends AView;


function FooterView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function FooterView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function FooterView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
