
/**
Constructor
Do not call Function in Constructor.
*/
class HistoryView()
{
	super();

	//TODO:edit here

}
extends AView;


function HistoryView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function HistoryView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function HistoryView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
