
/**
Constructor
Do not call Function in Constructor.
*/
class IntroduceView()
{
	super();

	//TODO:edit here

}
extends AView;


function IntroduceView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function IntroduceView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function IntroduceView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
